services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: calls
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d calls"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    volumes:
      - .:/code
      - recordings:/recordings
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8000:8000"

  worker:
    build: .
    command: celery -A app.core.celery_app worker -l info
    env_file:
      - .env
    volumes:
      - .:/code
      - recordings:/recordings
    depends_on:
      api:
        condition: service_started
      redis:
        condition: service_started
      db:
        condition: service_healthy

  beat:
    build: .
    command: celery -A app.core.celery_app beat -l info
    env_file:
      - .env
    depends_on:
      worker:
        condition: service_started

volumes:
  db_data:
  recordings:
